before:
  hooks:
    - go mod download
builds:
  - dir: cmd/matrixcli
    main: main.go
    binary: matrixcli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
gitlab_urls:
  api: https://gitlab.node-3.net/api/v4/
  download: https://gitlab.node-3.net
